#
# adobe_scanner-config.yaml
#
# OctoSAM Adobe Cloud Scanner Script Sample Configuration File
#
# UMAPI 3.0 Using OAuth 2.0
#
# https://adobe-apiplatform.github.io/umapi-documentation/en/UM_Authentication.html
#
# the scanner reads the file either from the current directory or from OCTOSAM_CONFIGURATION_FOLDER if found there
#

org_id: ....@AdobeOrg

client_id: ....
client_secret: .....

#
# if storing the client secret in the Windows credential manager:
# client_secret_credential_manager_target: octosam_adobe_scanner
#

#
# scanner configuration:
# configure output folder if you do not want to specify it on the command-line
#
output_folder: D:/OctoSAM/Shared/Data

#
# configure log folder if you do not want to specify it on the command-line
#

log_folder: D:/OctoSAM/Logs



